version: '3.7'

networks:
  default:

volumes:
  redis:
  store:

services:
  caddy:
    image: ${CADDY_IMAGE}
    deploy:
      mode: replicated
    # This port format is needed to get real ip address of the client
    ports:
      - target: 80
        published: 80
        mode: ingress
      - target: 443
        published: 443
        mode: ingress
    volumes:
      - ./Caddyfile:/Caddyfile

  redis:
    image: 'redis:6-alpine'
    volumes:
      - redis:/data

  relay:
    image: ${RELAY_IMAGE}
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis

  store:
    image: sebohe/waku:master
    volumes:
      - store:/store
    command:
      - --nodekey=1107ad8e44fe7dc924bb9d388d588832cdc4273efb2623e8609c8085d0d2154c
      - --peerpersist=true
      - --relay=true
      - --store=true
      - --filter=true
      - --dbpath=/store
      - --topics=6d9b0b4b9994e8a6afbd3dc3ed983cd51c755afb27cd1dc7825ef59c134a39f7
