version: '3.7'

services:
  nginx:
    environment:
      DOMAIN_URL: ${RELAY_URL}
      APP_ENV: production
      EMAIL: ${CERTBOT_EMAIL}
      CONTAINER_NAME: relay
      APP_PORT: 5000
      APP_QTY: 1
      CLOUDFLARE: ${CLOUDFLARE}
    depends_on:
      - relay

  relay:
    image: ${RELAY_IMAGE}
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379/0
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1.5G
