version: '3.7'

services:
  nginx:
    environment:
      DOMAIN_URL: ${BRIDGE_URL}
      APP_ENV: production
      EMAIL: ${CERTBOT_EMAIL}
      CONTAINER_NAME: bridge
      APP_PORT: 5000
      APP_QTY: 2
      CLOUDFLARE: ${CLOUDFLARE}
    depends_on:
      - relay

  relay:
    image: ${RELAY_IMAGE}
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379/0
