version: '3.9'

networks:
  default:

volumes:
  redis:
  store:
  wakuids:

services:
  caddy:
    image: ${CADDY_IMAGE}
    deploy:
      mode: replicated
    # Port mode must be mode: host to allow access to the external ip
    ports:
      - target: 80
        published: 80
        mode: ingress
      - target: 443
        published: 443
        mode: ingress
    volumes:
      - ./Caddyfile:/Caddyfile

  redis:
    image: 'redis:6-alpine'
    volumes:
      - redis:/data

  store:
    image: ${WAKU_IMAGE}
    environment:
      STORE: 1
    volumes:
      - store:/store

  waku:
    image: ${WAKU_IMAGE}
    hostname: "waku.{{.Task.Slot}}"

  relay:
    image: ${RELAY_IMAGE}
    environment:
      NODE_ENV: development
      REDIS_URL: "redis://redis:6379/{{.Task.Slot}}"
      WAKU_URL: "http://waku.{{.Task.Slot}}:8545"
