global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s

scrape_configs:
- job_name: docker_host
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: [ "172.18.0.1:9323" ]

- job_name: caddy
  metrics_path: /metrics
  static_configs:
  - targets: [ "caddy:9321" ]

- job_name: node_exporter
  static_configs:
  - targets: ['node_exporter:9100']

- job_name: cadvisor
  static_configs:
  - targets: [ "cadvisor:8080" ]

- job_name: redis_exporter
  static_configs:
  - targets: ['redis_exporter:9121']

- job_name: relay
  metrics_path: /metrics
  static_configs:
  - targets: ['relay:5000']

- job_name: waku
  metrics_path: /metrics
  static_configs:
  - targets: ['waku:9001']
