name: Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v9
        with:
          name: walletconnect
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: |
          docker version
          docker swarm init 2> /dev/null || true
      - run: make ci
      - name: Print logs
        if: failure()
        run: docker service logs --tail 200 walletconnect_caddy && docker service logs --tail 200 walletconnect_relay
      - run: make cachix
