name: Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make dev &
      - run: sleep 30 && make test-client
      - run: make test-relay
